apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  labels:
    app: proxy-service
spec:
  type: ClusterIP
  ports:
  - name: {{ .Values.proxyService.port9443 | quote }}
    port: {{ .Values.proxyService.port9443 }}
    targetPort: {{ .Values.proxyService.port9443 }}
  selector:
    app: proxy-service