apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  labels:
    app: proxy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      hostname: proxy-service
      containers:
      - name: proxy-service
        image: "{{ .Values.containerimages.iiotServicesRegistry }}/{{ .Values.containerimages.iiotServicesRepoPrefix }}/{{ .Values.containerimages.iiotServicesRepos.proxyServiceRepo }}:{{ index .Values.containerimages.tags.iiotServices }}"
        imagePullPolicy: {{ .Values.containerimages.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.proxyService.port9443 }}
        volumeMounts:
        - mountPath: /var/iiot-services-data
          name: iiot-services-data
        env:
        - name: PROXYSERVICE_SgSystemConfiguration__AdminUser
          valueFrom:
            secretKeyRef:
              name: persistence-service-credentials
              key: username
        - name: PROXYSERVICE_SgSystemConfiguration__AdminUserPassword
          valueFrom:
            secretKeyRef:
              name: persistence-service-credentials
              key: password
        - name: PROXYSERVICE_SgSystemConfiguration__DatabaseUri
          valueFrom:
            secretKeyRef:
              name: persistence-service-credentials
              key: mongodb-uri
        - name: PROXYSERVICE_Redis__Host
          value: {{ .Values.redis.hostname }}
        - name: IIOT_SERVICES_URL
          value: {{ .Values.ingress.iiotServicesDomain }}
        - name: PROXYSERVICE_HostingInformationConfiguration__Uri
          {{ if eq (int .Values.proxyService.port9443) 443 }}
          value: "https://{{ .Values.ingress.iiotServicesDomain }}"
          {{ else }}
          value: "https://{{ .Values.ingress.iiotServicesDomain }}:{{ .Values.proxyService.port9443 }}"
          {{ end }}
        - name: PROXYSERVICE_Kestrel__Endpoints__Https__Url
          value: "https://*:{{ .Values.proxyService.port9443 }}"
      restartPolicy: Always
      imagePullSecrets: {{ toYaml .Values.containerimages.imagePullSecrets | nindent 8 }}
{{ if .Values.enableNodeSelectorLinux}}
      nodeSelector:
        kubernetes.io/os: linux
{{ end }}
      volumes:
      - name: iiot-services-data
        persistentVolumeClaim:
          claimName: {{ .Values.sharedVolume.name }}