apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-management
  labels:
    app: device-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-management
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: device-management
    spec:
      containers:
      - name: device-management
        image: "{{ .Values.containerimages.iiotServicesRegistry }}/{{ .Values.containerimages.iiotServicesRepoPrefix }}/{{ index .Values.containerimages.iiotServicesRepos.deviceManagementRepo }}:{{ index .Values.containerimages.tags.iiotServices }}"
        imagePullPolicy: {{ .Values.containerimages.imagePullPolicy }}
        env:
        - name: DEVICE_MANAGEMENT_SgSystemConfiguration__AdminUser
          valueFrom:
            secretKeyRef:
              name: persistence-service-credentials
              key: username
        - name: DEVICE_MANAGEMENT_SgSystemConfiguration__AdminUserPassword
          valueFrom:
            secretKeyRef:
              name: persistence-service-credentials
              key: password
        - name: DEVICE_MANAGEMENT_SgSystemConfiguration__DatabaseUri
          valueFrom:
            secretKeyRef:
              name: persistence-service-credentials
              key: mongodb-uri
        - name: DEVICE_MANAGEMENT_Redis__Host
          value: {{ .Values.redis.hostname }}
        ports:
        - containerPort: 9415
        volumeMounts:
        - mountPath: /var/iiot-services-data
          name: iiot-services-data
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: {{ .Values.healthprobes.startupDelay }}
          periodSeconds: {{ .Values.healthprobes.pollingPeriod }}
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: {{ .Values.healthprobes.startupDelay }}
          periodSeconds: {{ .Values.healthprobes.pollingPeriod }}
      restartPolicy: Always
      imagePullSecrets: {{ toYaml .Values.containerimages.imagePullSecrets | nindent 8 }}
{{ if .Values.enableNodeSelectorLinux}}
      nodeSelector:
        kubernetes.io/os: linux
{{ end }}
      volumes:
      - name: iiot-services-data
        persistentVolumeClaim:
          claimName: {{ .Values.sharedVolume.name }}