apiVersion: v1
kind: Service
metadata:
  name: iiot-services-redis
  labels:
    app: iiot-services-redis
spec:
  type: ClusterIP
  ports:
  - name: "6379"
    port: {{ .Values.redis.redisPort6379 }}
    targetPort: 6379
  selector:
    app: iiot-services-redis