apiVersion: v1
kind: Service
metadata:
  name: certificate-management
  labels:
    app: certificate-management
spec:
  type: ClusterIP
  selector:
    app: certificate-management
  ports:
  - name: "9410"
    targetPort: 9410
    port: {{ .Values.certificateManagement.port9410 }}
  - name: "9412"
    targetPort: 9412
    port: {{ .Values.certificateManagement.port9412 }}