apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-storage
  name: data-storage
spec:
  type: ClusterIP
  ports:
  - name: "9460"
    port: {{ .Values.dataStorage.port9460 }}
    targetPort: 9460
  selector:
    app: data-storage