apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-configuration-studio
  labels:
    app: service-configuration-studio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-configuration-studio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service-configuration-studio
    spec:
      containers:
      - name: service-configuration-studio
        image: "{{ .Values.containerimages.iiotServicesRegistry }}/{{ .Values.containerimages.iiotServicesRepoPrefix }}/{{ index .Values.containerimages.iiotServicesRepos.serviceConfigurationStudioRepo }}:{{ index .Values.containerimages.tags.iiotServices }}"
        imagePullPolicy: {{ .Values.containerimages.imagePullPolicy }}
        env:
        - name: SERVICECONFIGURATIONSTUDIO_SgSystemConfiguration__AdminUser
          valueFrom:
            secretKeyRef:
              name: persistence-service-credentials
              key: username
        - name: SERVICECONFIGURATIONSTUDIO_SgSystemConfiguration__AdminUserPassword
          valueFrom:
            secretKeyRef:
              name: persistence-service-credentials
              key: password
        - name: SERVICECONFIGURATIONSTUDIO_SgSystemConfiguration__DatabaseUri
          valueFrom:
            secretKeyRef:
              name: persistence-service-credentials
              key: mongodb-uri
        - name: SERVICECONFIGURATIONSTUDIO_Redis__Host
          value: {{ .Values.redis.hostname }}
        ports:
        - containerPort: 9450
        volumeMounts:
        - mountPath: /var/iiot-services-data
          name: iiot-services-data
      restartPolicy: Always
      imagePullSecrets: {{ toYaml .Values.containerimages.imagePullSecrets | nindent 8 }}
{{ if .Values.enableNodeSelectorLinux}}
      nodeSelector:
        kubernetes.io/os: linux
{{ end }}
      volumes:
      - name: iiot-services-data
        persistentVolumeClaim:
          claimName: {{ .Values.sharedVolume.name }}