apiVersion: v1
kind: Service
metadata:
  name: service-configuration-studio
  labels:
    app: service-configuration-studio
spec:
  type: ClusterIP
  ports:
  - name: "9450"
    port: {{ .Values.serviceConfigurationStudio.port9450 }}
    targetPort: 9450
  selector:
    app: service-configuration-studio