apiVersion: v1
kind: Service
metadata:
  name: iiot-api
  labels:
    app: iiot-api
spec:
  type: ClusterIP
  ports:
  - name: "9400"
    port: {{ .Values.iiotApi.port9400 }}
    targetPort: 9400
  selector:
    app: iiot-api