{{ if .Values.ingress.enableIngress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iiot-services-https
  annotations:
    kubernetes.io/ingress.class: nginx
    #cert-manager.io/cluster-issuer: "letsencrypt-staging"
    #cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" # required as the backend services handle TLS on their own
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k" # required as the header from configuration backend is too big for the default 4k of the ingress
    nginx.ingress.kubernetes.io/proxy-body-size: 16m # required for evacuating large data amounts to the data storage
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"

    # session affinity:
    # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#session-affinity
    # TODO: check if required
    # nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    # nginx.ingress.kubernetes.io/affinity: "cookie"
    
spec:
  tls:
  # - hosts:
  #   - {{ .Values.ingress.iiotServicesDomain }}
  #   secretName: tls-secret-iiot-services-https
  rules:
  - host: {{ .Values.ingress.iiotServicesDomain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: proxy-service
            port:
              number: {{ .Values.proxyService.port9443 }}
    {{if not .Values.ingress.enableProxyService}}
      # TODO: put additional ingress rules here
    {{end}}
{{ end }}