apiVersion: v1
kind: Secret
metadata:
  name: persistence-service-credentials
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.persistenseService.mongodb.user.username }}
  password: {{ .Values.persistenseService.mongodb.user.password }}
  replicasetkey: {{ .Values.persistenseService.mongodb.replicaSetKey }}
  mongodb-uri: {{ with .Values.persistenseService.mongodb -}}
  {{- list "mongodb://" .dbHostname ":" .dbPort | join "" | quote }}
{{- end }}
#TODO: add replica set to uri? does it need code changes in the services?